In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/wine-quality-preprocessed.csv')
df.head()

,volatile acidity,residual sugar,chlorides,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0.70,0.641854,-2.577022,3.526361,0.9978,3.51,0.56,2.240710,0
1,0.88,0.955511,-2.322788,4.204693,0.9968,3.20,0.68,2.282382,0
2,0.76,0.832909,-2.385967,3.988984,0.9970,3.26,0.65,2.282382,0
3,0.28,0.641854,-2.590267,4.094345,0.9980,3.16,0.58,2.282382,1
4,0.70,0.641854,-2.577022,3.526361,0.9978,3.51,0.56,2.240710,0

In [11]:
df[(df['quality'] > 0)]

,volatile acidity,residual sugar,chlorides,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3,0.28,0.641854,-2.590267,4.094345,0.99800,3.16,0.58,2.282382,1
7,0.65,0.182322,-2.733368,3.044522,0.99460,3.39,0.47,2.302585,1
8,0.58,0.693147,-2.617296,2.890372,0.99680,3.36,0.57,2.251292,1
14,0.28,0.587787,-2.385967,4.634729,0.99690,3.30,0.75,2.351375,1
16,0.22,0.587787,-2.563950,4.094345,0.99680,3.39,0.53,2.240710,1
...,...,...,...,...,...,...,...,...,...
1471,0.51,0.832909,-2.577022,3.688879,0.99574,3.42,0.75,2.397895,1
1472,0.62,0.641854,-2.688248,3.637586,0.99651,3.42,0.82,2.251292,1
1474,0.55,0.788457,-2.780621,3.931826,0.99512,3.52,0.76,2.415914,1
1475,0.51,0.832909,-2.577022,3.688879,0.99574,3.42,0.75,2.397895,1
1477,0.31,1.280934,-2.703063,3.737670,0.99549,3.39,0.66,2.397895,1

In [32]:
def prior_probability(df, label):
    p = df[label][(df[label] == 1)].count()
    n = df[label].count()
    return [p/n, 1-p/n]

def likelyhood_probability(df, feature,x, label):
    #only considering values with given outcome
    df = df[(df['quality'] == label)]
    mean = df[feature].mean()
    sd = df[feature].std()
    #build gaussian distribution PDF
    prob = (1 / (sd * np.sqrt(2 * np.pi))) * (np.exp(-(1/2) * ((x-mean)/sd)**2))
    return prob


def naive_bayes (df, X):
    features = list(X.columns)
    prior = prior_probability(df, 'quality')
    y_pred = []
    for x in X:
        print(x)
        likelyhood = [1,1]
        for l in range(2):
            for f in range(len(features)):
                print(x[f])
                likelyhood[l] *= likelyhood_probability(df, features[f],x[f],l)
        
        post = [0,0]
        for l in range(2):
            post[l] = likelyhood[l] * prior[l]
        
        y_pred.apped(np.argmax(post))
    return np.array(y_pred)

In [33]:
X = df.loc[:, df.columns != 'quality']
naive_bayes(df,X)

volatile acidity
v

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U1'), dtype('float64')) -> None