In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('/Users/luzi/Desktop/pythonAssignement/ml-exercises/data/dow-jones/dow_jones_index.csv')

In [10]:
df.head(50)

,quarter,stock,date,open,high,low,close,volume,percent_change_price,percent_change_volume_over_last_wk,previous_weeks_volume,next_weeks_open,next_weeks_close,percent_change_next_weeks_price,days_to_next_dividend,percent_return_next_dividend
0,1,AA,1/7/2011,$15.82,$16.72,$15.78,$16.42,239655616,3.792670,NaN,NaN,$16.71,$15.97,-4.428490,26,0.182704
1,1,AA,1/14/2011,$16.71,$16.71,$15.64,$15.97,242963398,-4.428490,1.380223,2.396556e+08,$16.19,$15.79,-2.470660,19,0.187852
2,1,AA,1/21/2011,$16.19,$16.38,$15.60,$15.79,138428495,-2.470660,-43.024959,2.429634e+08,$15.87,$16.13,1.638310,12,0.189994
3,1,AA,1/28/2011,$15.87,$16.63,$15.82,$16.13,151379173,1.638310,9.355500,1.384285e+08,$16.18,$17.14,5.933250,5,0.185989
4,1,AA,2/4/2011,$16.18,$17.39,$16.18,$17.14,154387761,5.933250,1.987452,1.513792e+08,$17.33,$17.37,0.230814,97,0.175029
5,1,AA,2/11/2011,$17.33,$17.48,$16.97,$17.37,114691279,0.230814,-25.712195,1.543878e+08,$17.39,$17.28,-0.632547,90,0.172712
6,1,AA,2/18/2011,$17.39,$17.68,$17.28,$17.28,80023895,-0.632547,-30.226696,1.146913e+08,$16.98,$16.68,-1.766780,83,0.173611
7,1,AA,2/25/2011,$16.98,$17.15,$15.96,$16.68,132981863,-1.766780,66.177694,8.002390e+07,$16.81,$16.58,-1.368230,76,0.179856
8,1,AA,3/4/2011,$16.81,$16.94,$16.13,$16.58,109493077,-1.368230,-17.663150,1.329819e+08,$16.58,$16.03,-3.317250,69,0.180941
9,1,AA,3/11/2011,$16.58,$16.75,$15.42,$16.03,114332562,-3.317250,4.419900,1.094931e+08,$15.95,$16.11,1.003130,62,0.187149
10,1,AA,3/18/2011,$15.95,$16.33,$15.43,$16.11,130374108,1.003130,14.030601,1.143326e+08,$16.38,$17.09,4.334550,55,0.186220
11,1,AA,3/25/2011,$16.38,$17.24,$16.26,$17.09,95550392,4.334550,-26.710607,1.303741e+08,$17.13,$17.47,1.984820,48,0.175541
12,1,AXP,1/7/2011,$43.30,$45.60,$43.11,$44.36,45102042,2.448040,NaN,NaN,$44.20,$46.25,4.638010,89,0.405771
13,1,AXP,1/14/2011,$44.20,$46.25,$44.01,$46.25,25913713,4.638010,-42.544258,4.510204e+07,$46.03,$46.00,-0.065175,82,0.389189
14,1,AXP,1/21/2011,$46.03,$46.71,$44.71,$46.00,38824728,-0.065175,49.823099,2.591371e+07,$46.05,$43.86,-4.755700,75,0.391304
15,1,AXP,1/28/2011,$46.05,$46.27,$43.42,$43.86,51427274,-4.755700,32.460101,3.882473e+07,$44.13,$43.82,-0.702470,68,0.410397
16,1,AXP,2/4/2011,$44.13,$44.23,$43.15,$43.82,39501680,-0.702470,-23.189240,5.142727e+07,$43.96,$46.75,6.346680,61,0.410771
17,1,AXP,2/11/2011,$43.96,$46.79,$43.88,$46.75,43746998,6.346680,10.747183,3.950168e+07,$46.42,$45.53,-1.917280,54,0.385027
18,1,AXP,2/18/2011,$46.42,$46.93,$45.53,$45.53,28564910,-1.917280,-34.704297,4.374700e+07,$44.94,$43.53,-3.137520,47,0.395344
19,1,AXP,2/25/2011,$44.94,$45.12,$43.01,$43.53,39654146,-3.137520,38.821183,2.856491e+07,$43.73,$43.72,-0.022868,40,0.413508
20,1,AXP,3/4/2011,$43.73,$44.68,$42.75,$43.72,38985037,-0.022868,-1.687362,3.965415e+07,$43.86,$44.28,0.957592,33,0.411711
21,1,AXP,3/11/2011,$43.86,$45.54,$43.53,$44.28,37613429,0.957592,-3.518293,3.898504e+07,$43.86,$44.17,0.706794,26,0.406504
22,1,AXP,3/18/2011,$43.86,$44.47,$42.19,$44.17,41757526,0.706794,11.017600,3.761343e+07,$44.75,$45.59,1.877090,19,0.407516
23,1,AXP,3/25/2011,$44.75,$45.61,$44.10,$45.59,30798332,1.877090,-26.244835,4.175753e+07,$45.54,$45.36,-0.395257,12,0.394823
24,1,BA,1/7/2011,$66.15,$70.10,$66.00,$69.38,36258120,4.882840,NaN,NaN,$69.42,$70.07,0.936330,33,0.605362
25,1,BA,1/14/2011,$69.42,$70.50,$68.35,$70.07,18834664,0.936330,-48.053942,3.625812e+07,$70.86,$71.68,1.157210,26,0.599401
26,1,BA,1/21/2011,$70.86,$72.99,$70.23,$71.68,29594221,1.157210,57.126355,1.883466e+07,$71.52,$69.23,-3.201900,19,0.585938
27,1,BA,1/28/2011,$71.52,$72.82,$69.00,$69.23,34929673,-3.201900,18.028696,2.959422e+07,$69.26,$71.38,3.060930,12,0.606673
28,1,BA,2/4/2011,$69.26,$71.64,$69.12,$71.38,22770062,3.060930,-34.811694,3.492967e+07,$71.43,$72.14,0.993980,5,0.588400
29,1,BA,2/11/2011,$71.43,$72.99,$71.15,$72.14,21809411,0.993980,-4.218921,2.277006e+07,$72.70,$73.04,0.467675,89,0.582201
30,1,BA,2/18/2011,$72.70,$73.04,$71.09,$73.04,15989248,0.467675,-26.686475,2.180941e+07,$72.35,$72.30,-0.069109,82,0.575027
31,1,BA,2/25/2011,$72.35,$74.29,$70.00,$72.30,26258425,-0.069109,64.225516,1.598925e+07,$72.47,$71.80,-0.924520,75,0.580913
32,1,BA,3/4/2011,$72.47,$72.90,$68.60,$71.80,27527285,-0.924520,4.832201,2.625842e+07,$71.60,$71.64,0.055866,68,0.584958
33,1,BA,3/11/2011,$71.60,$72.50,$69.91,$71.64,25556296,0.055866,-7.160129,2.752728e+07,$71.17,$69.10,-2.908530,61,0.586265
34,1,BA,3/18/2011,$71.17,$71.23,$67.34,$69.10,29746370,-2.908530,16.395467,2.555630e+07,$70.29,$73.34,4.339170,54,0.607815
35,1,BA,3/25/2011,$70.29,$73.50,$70.03,$73.34,24423545,4.339170,-17.894032,2.974637e+07,$73.50,$74.01,0.693878,47,0.572675
36,1,BAC,1/7/2011,$13.85,$14.69,$13.80,$14.25,1453438639,2.888090,NaN,NaN,$14.17,$15.25,7.621740,54,0.070175
37,1,BAC,1/14/2011,$14.17,$15.25,$14.09,$15.25,760935694,7.621740,-47.645833,1.453439e+09,$15.08,$14.25,-5.503980,47,0.065574
38,1,BAC,1/21/2011,$15.08,$15.16,$13.94,$14.25,982445809,-5.503980,29.110228,7.609357e+08,$14.25,$13.60,-4.561400,40,0.070175
39,1,BAC,1/28/2011,$14.25,$14.26,$13.40,$13.60,1054415375,-4.561400,7.325551,9.824458e+08,$13.71,$14.29,4.230490,33,0.073529
40,1,BAC,2/4/2011,$13.71,$14.47,$13.64,$14.29,757192224,4.230490,-28.188431,1.054415e+09,$14.51,$14.77,1.791870,26,0.069979
41,1,BAC,2/11/2011,$14.51,$14.87,$14.35,$14.77,746465458,1.791870,-1.416650,7.571922e+08,$14.77,$14.75,-0.135410,19,0.067705
42,1,BAC,2/18/2011,$14.77,$14.95,$14.69,$14.75,458423511,-0.135410,-38.587445,7.464655e+08,$14.38,$14.20,-1.251740,12,0.067797
43,1,BAC,2/25/2011,$14.38,$14.52,$13.79,$14.20,712456757,-1.251740,55.414533,4.584235e+08,$14.27,$14.12,-1.051160,5,0.070422
44,1,BAC,3/4/2011,$14.27,$14.48,$13.81,$14.12,699671790,-1.051160,-1.794490,7.124568e+08,$14.18,$14.38,1.410440,89,0.070821
45,1,BAC,3/11/2011,$14.18,$14.70,$13.92,$14.38,805210688,1.410440,15.084058,6.996718e+08,$14.26,$14.04,-1.542780,82,0.069541
46,1,BAC,3/18/2011,$14.26,$14.35,$13.66,$14.04,792380862,-1.542780,-1.593350,8.052107e+08,$14.20,$13.34,-6.056340,75,0.071225
47,1,BAC,3/25/2011,$14.20,$14.22,$13.32,$13.34,717678994,-6.056340,-9.427520,7.923809e+08,$13.42,$13.37,-0.372578,68,0.074963
48,1,CAT,1/7/2011,$94.38,$94.81,$92.30,$93.73,24135903,-0.688705,NaN,NaN,$93.21,$94.01,0.858277,11,0.469433
49,1,CAT,1/14/2011,$93.21,$94.70,$92.51,$94.01,19707235,0.858277,-18.348880,2.413590e+07,$94.16,$92.75,-1.497450,4,0.468035

In [14]:
df['open'] = df['open'].str.replace("$",'').astype(float)

/var/folders/60/b59yh0f10dn10yn_3tns4q84r1cn7t/T/ipykernel_6602/2079442187.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['open'] = df['open'].str.replace("$",'').astype(float)

In [15]:
df.head(5)

,quarter,stock,date,open,high,low,close,volume,percent_change_price,percent_change_volume_over_last_wk,previous_weeks_volume,next_weeks_open,next_weeks_close,percent_change_next_weeks_price,days_to_next_dividend,percent_return_next_dividend
0,1,AA,1/7/2011,15.82,$16.72,$15.78,$16.42,239655616,3.79267,NaN,NaN,$16.71,$15.97,-4.428490,26,0.182704
1,1,AA,1/14/2011,16.71,$16.71,$15.64,$15.97,242963398,-4.42849,1.380223,239655616.0,$16.19,$15.79,-2.470660,19,0.187852
2,1,AA,1/21/2011,16.19,$16.38,$15.60,$15.79,138428495,-2.47066,-43.024959,242963398.0,$15.87,$16.13,1.638310,12,0.189994
3,1,AA,1/28/2011,15.87,$16.63,$15.82,$16.13,151379173,1.63831,9.355500,138428495.0,$16.18,$17.14,5.933250,5,0.185989
4,1,AA,2/4/2011,16.18,$17.39,$16.18,$17.14,154387761,5.93325,1.987452,151379173.0,$17.33,$17.37,0.230814,97,0.175029

In [16]:
df['high'] = df['high'].str.replace("$",'').astype(float)

df['low'] = df['low'].str.replace("$",'').astype(float)

df['close'] = df['close'].str.replace("$",'').astype(float)

/var/folders/60/b59yh0f10dn10yn_3tns4q84r1cn7t/T/ipykernel_6602/1346281168.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['high'] = df['high'].str.replace("$",'').astype(float)
/var/folders/60/b59yh0f10dn10yn_3tns4q84r1cn7t/T/ipykernel_6602/1346281168.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['low'] = df['low'].str.replace("$",'').astype(float)
/var/folders/60/b59yh0f10dn10yn_3tns4q84r1cn7t/T/ipykernel_6602/1346281168.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['close'] = df['close'].str.replace("$",'').astype(float)

In [17]:
df.head(5)

,quarter,stock,date,open,high,low,close,volume,percent_change_price,percent_change_volume_over_last_wk,previous_weeks_volume,next_weeks_open,next_weeks_close,percent_change_next_weeks_price,days_to_next_dividend,percent_return_next_dividend
0,1,AA,1/7/2011,15.82,16.72,15.78,16.42,239655616,3.79267,NaN,NaN,$16.71,$15.97,-4.428490,26,0.182704
1,1,AA,1/14/2011,16.71,16.71,15.64,15.97,242963398,-4.42849,1.380223,239655616.0,$16.19,$15.79,-2.470660,19,0.187852
2,1,AA,1/21/2011,16.19,16.38,15.60,15.79,138428495,-2.47066,-43.024959,242963398.0,$15.87,$16.13,1.638310,12,0.189994
3,1,AA,1/28/2011,15.87,16.63,15.82,16.13,151379173,1.63831,9.355500,138428495.0,$16.18,$17.14,5.933250,5,0.185989
4,1,AA,2/4/2011,16.18,17.39,16.18,17.14,154387761,5.93325,1.987452,151379173.0,$17.33,$17.37,0.230814,97,0.175029

In [18]:
df1= df.dropna()

In [19]:
df1

,quarter,stock,date,open,high,low,close,volume,percent_change_price,percent_change_volume_over_last_wk,previous_weeks_volume,next_weeks_open,next_weeks_close,percent_change_next_weeks_price,days_to_next_dividend,percent_return_next_dividend
1,1,AA,1/14/2011,16.71,16.71,15.64,15.97,242963398,-4.428490,1.380223,239655616.0,$16.19,$15.79,-2.470660,19,0.187852
2,1,AA,1/21/2011,16.19,16.38,15.60,15.79,138428495,-2.470660,-43.024959,242963398.0,$15.87,$16.13,1.638310,12,0.189994
3,1,AA,1/28/2011,15.87,16.63,15.82,16.13,151379173,1.638310,9.355500,138428495.0,$16.18,$17.14,5.933250,5,0.185989
4,1,AA,2/4/2011,16.18,17.39,16.18,17.14,154387761,5.933250,1.987452,151379173.0,$17.33,$17.37,0.230814,97,0.175029
5,1,AA,2/11/2011,17.33,17.48,16.97,17.37,114691279,0.230814,-25.712195,154387761.0,$17.39,$17.28,-0.632547,90,0.172712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,2,XOM,5/27/2011,80.22,82.63,80.07,82.63,68230855,3.004240,-21.355713,86758820.0,$83.28,$81.18,-2.521610,75,0.568801
746,2,XOM,6/3/2011,83.28,83.75,80.18,81.18,78616295,-2.521610,15.221032,68230855.0,$80.93,$79.78,-1.420980,68,0.578960
747,2,XOM,6/10/2011,80.93,81.87,79.72,79.78,92380844,-1.420980,17.508519,78616295.0,$80.00,$79.02,-1.225000,61,0.589120
748,2,XOM,6/17/2011,80.00,80.82,78.33,79.02,100521400,-1.225000,8.811952,92380844.0,$78.65,$76.78,-2.377620,54,0.594786
749,2,XOM,6/24/2011,78.65,81.12,76.78,76.78,118679791,-2.377620,18.064204,100521400.0,$76.88,$82.01,6.672740,47,0.612139

In [24]:
import numpy as np
from scipy import stats

df1[(np.abs(stats.zscore(df)) < 3).all(axis=1)]

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [23]:
df1.head(5)

,quarter,stock,date,open,high,low,close,volume,percent_change_price,percent_change_volume_over_last_wk,previous_weeks_volume,next_weeks_open,next_weeks_close,percent_change_next_weeks_price,days_to_next_dividend,percent_return_next_dividend
1,1,AA,1/14/2011,16.71,16.71,15.64,15.97,242963398,-4.428490,1.380223,239655616.0,$16.19,$15.79,-2.470660,19,0.187852
2,1,AA,1/21/2011,16.19,16.38,15.60,15.79,138428495,-2.470660,-43.024959,242963398.0,$15.87,$16.13,1.638310,12,0.189994
3,1,AA,1/28/2011,15.87,16.63,15.82,16.13,151379173,1.638310,9.355500,138428495.0,$16.18,$17.14,5.933250,5,0.185989
4,1,AA,2/4/2011,16.18,17.39,16.18,17.14,154387761,5.933250,1.987452,151379173.0,$17.33,$17.37,0.230814,97,0.175029
5,1,AA,2/11/2011,17.33,17.48,16.97,17.37,114691279,0.230814,-25.712195,154387761.0,$17.39,$17.28,-0.632547,90,0.172712